const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Платформер2: 0},
	{СледитьЗа: 0},
	{Игрок: 0},
	{Твердый: 0},
	{Спрайт2: 0},
	{ТайловыйФон: 0},
	{ТайловыйФон3: 0},
	{ТайловыйФон4: 0},
	{ТайловыйФон7: 0},
	{ТайловыйФон8: 0},
	{ТайловыйФон9: 0},
	{ТайловыйФон10: 0},
	{ТайловыйФон11: 0},
	{ТайловыйФон13: 0},
	{Телепорт1: 0},
	{Спрайт4: 0},
	{Монетка: 0},
	{Якорь: 0},
	{Монетка2: 0},
	{Текст: 0},
	{ТайловыйФон16: 0},
	{Спрайт5: 0},
	{Платформер: 0},
	{Дракон: 0},
	{Клавиатура: 0},
	{Пуля: 0},
	{Стрела: 0},
	{Стрела2: 0},
	{Частицы: 0},
	{Частицы2: 0},
	{Телепорт2: 0},
	{ОбычнаяДверь: 0},
	{ТайловыйФон21: 0},
	{ТайловыйФон23: 0},
	{ТайловыйФон22: 0},
	{ТайловыйФон24: 0},
	{ТайловыйФон2: 0},
	{ТайловыйФон5: 0},
	{ТайловыйФон6: 0},
	{Спрайт: 0},
	{Спрайт3: 0},
	{Спрайт6: 0},
	{Телепорт3: 0},
	{Спрайт7: 0},
	{Телепорт4: 0},
	{Переменная1: 0}
];

self.InstanceType = {
	Игрок: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон7: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон8: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон9: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон10: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон11: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон13: class extends self.ITiledBackgroundInstance {},
	Телепорт1: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Монетка: class extends self.ISpriteInstance {},
	Монетка2: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	ТайловыйФон16: class extends self.ITiledBackgroundInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Дракон: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Стрела: class extends self.ISpriteInstance {},
	Стрела2: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Телепорт2: class extends self.ISpriteInstance {},
	ОбычнаяДверь: class extends self.ISpriteInstance {},
	ТайловыйФон21: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон23: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон22: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон24: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Телепорт3: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Телепорт4: class extends self.ISpriteInstance {}
}